env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh
script:
  - rustc --version
  - cargo --version
  - make
  - make check
notifications:
    email:
        - damien.schoof+github@gmail.com
